- name: yum install dependency
  yum: name={{item}}
  with_items:
    - cmake
    - libaio-devel
    - numactl-devel
    - ncurses-devel
    - gcc-c++
    - gcc
    - bison
    - perl-Module-Install.noarch
- name: create user mysql
  user:
    name: mysql
    createhome: no
    shell: /sbin/nologin
- name: tar mysql
  unarchive:
    src: mysql-5.6.39.tar.gz 
    dest: /usr/local/src/
    copy: yes
- name: mkdir log
  file:
    path: /data/log
    state: directory
    mode: 0755
    owner: mysql
    group: mysql
- name: mkdir datadir
  file:
    path: /data/mysql
    state: directory
    mode: 0755
    owner: mysql
    group: mysql
- name: mkdir tmp
  file:
    path: /data/tmp
    state: directory
    mode: 0755
    owner: mysql
    group: mysql
- name: install mysql
  command: "{{item}}"
  with_items:
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local/mysql -DMYSQL_DATADIR=/data/mysql -DSYSCONFDIR=/etc -DWITH_INNOBASE_STORAGE_ENGINE=1 -DWITH_PERFSCHEMA_STORAGE_ENGINE=1 -DEXTRA_CHARSETS=all -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DWITH_DEBUG=0 -DBUILD_CONFIG=mysql_release -DFEATURE_SET=community -DWITH_EMBEDDED_SERVER=OFF -DMYSQL_UNIX_ADDR=/tmp/mysql.sock
    - make
    - make install
    - /usr/local/mysql/scripts/mysql_install_db --user=mysql --basedir=/usr/local/mysql --datadir=/data/mysql 
    - cp /usr/local/mysql/support-files/mysql.server /etc/rc.d/init.d/mysqld
  args:
    chdir: /usr/local/src/mysql-5.6.39
- name: init service
  shell: systemctl daemon-reload
- name: copy my.cnf
  template: 
    src: my.cnf.j2 
    dest: /etc/my.cnf
  notify: reload mysqld server  
- name: start mysql service
  service: 
    name: mysqld 
    state: started 
    enabled: yes
- name: config path
  lineinfile:
    path: /etc/profile
    line: export PATH=/usr/local/mysql/bin:$PATH
