- name: yum install dependency
  yum: name={{item}}
  with_items:
    - zlib-devel
    - libxml2-devel
    - libjpeg-turbo-devel
    - freetype-devel
    - libpng-devel
    - gd-devel
    - libcurl-devel
    - libxslt-devel
    - mcrypt
    - libmcrypt-devel
    - mhash
    - mhash-devel
    - openssl-devel
- name: tar php
  unarchive:
    src: php-5.6.34.tar.gz
    dest: /usr/local/src/
- name: install php
  shell: "{{item}}"
  with_items:
    - ./configure --prefix=/usr/local/php  --with-mysql=mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-iconv-dir=/usr/local/libiconv --with-freetype-dir --with-jpeg-dir --with-png-dir --with-zlib --with-libxml-dir=/usr --enable-xml --disable-rpath --enable-bcmath --enable-shmop --enable-sysvsem --enable-inline-optimization --with-curl --enable-mbregex --enable-fpm --enable-mbstring --with-mcrypt --with-gd --enable-gd-native-ttf --with-openssl --with-mhash --with-gettext --enable-pcntl --enable-sockets --with-xmlrpc --enable-soap --enable-short-tags --enable-static --with-xsl --with-fpm-user=nginx  --with-fpm-group=nginx  --enable-ftp --enable-opcache=yes
    - make
    - make install
  args:
    chdir: /usr/local/src/php-5.6.34
- name: copy php.ini
  copy:
    src: /usr/local/src/php-5.6.34/php.ini-production
    dest: /usr/local/php/lib/php.ini
- name: copy php-fpm.conf
  copy: 
    src: /usr/local/php/etc/php-fpm.conf.default 
    dest: /usr/local/php/etc/php-fpm.conf 
- name: copy start scripts 
  template: 
    src: php.j2 
    dest: /lib/systemd/system/php-fpm.service 
- name: start php service 
  service: 
    name: php-fpm 
    state: started 
    enabled: yes
- name: create link php-fpm
  file:
    src: /usr/local/php/sbin/php-fpm
    dest: /usr/local/sbin/php-fpm
    state: link
